// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.2_@vercel+functions@3.3.4_@aws-sdk+credential-provider-web-ident_b16b0d0f59f694580301add47f60a0ce/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vercel+functions@3.3.4_@aws-sdk+credential-provider-web-identity@3_79c540d00a087fb6dfbd6fb8c84b9f8b/node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
  }
}
export {}