/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'credits': RouteRecordInfo<
      'credits',
      '/credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'game': RouteRecordInfo<
      'game',
      '/game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'language': RouteRecordInfo<
      'language',
      '/language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'leaderboard': RouteRecordInfo<
      'leaderboard',
      '/leaderboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'players': RouteRecordInfo<
      'players',
      '/players',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'results': RouteRecordInfo<
      'results',
      '/results',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'round-start': RouteRecordInfo<
      'round-start',
      '/round-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings': RouteRecordInfo<
      'settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'pages/credits.vue': {
      routes:
        | 'credits'
      views:
        | never
    }
    'pages/game.vue': {
      routes:
        | 'game'
      views:
        | never
    }
    'pages/language.vue': {
      routes:
        | 'language'
      views:
        | never
    }
    'pages/leaderboard.vue': {
      routes:
        | 'leaderboard'
      views:
        | never
    }
    'pages/players.vue': {
      routes:
        | 'players'
      views:
        | never
    }
    'pages/results.vue': {
      routes:
        | 'results'
      views:
        | never
    }
    'pages/round-start.vue': {
      routes:
        | 'round-start'
      views:
        | never
    }
    'pages/settings.vue': {
      routes:
        | 'settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
