[project]
name = "cloudcrusaders"
version = "0.1.0"
description = "CloudCrusaders using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.8.1"
]

[project.scripts]
cloudcrusaders = "cloudcrusaders.main:run"
run_crew = "cloudcrusaders.main:run"
train = "cloudcrusaders.main:train"
replay = "cloudcrusaders.main:replay"
test = "cloudcrusaders.main:test"
run_with_trigger = "cloudcrusaders.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
