#!/usr/bin/env bash

# ===========================================
# AWS S3 + CloudFront Deployment Script
# ===========================================
# This script builds, tests and deploys the Guess Game PWA to AWS
# Usage: ./aws-deploy.sh [environment]
# Example: ./aws-deploy.sh production
#
# Environment Variables:
#   - AWS_S3_BUCKET: S3 bucket name (required)
#   - AWS_CLOUDFRONT_ID: CloudFront distribution ID (optional, for cache invalidation)
#   - AWS_REGION: AWS region (default: eu-central-1)
#   - SKIP_E2E_TESTS: Set to "true" to skip E2E test verification (default: false for local deployments)
#   - CI: Set automatically in CI/CD pipelines (skips pre-deployment checks and E2E tests)

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/scripts/lib.sh"
ensure_repo_root

# Configuration
ENVIRONMENT="${1:-production}"
BUILD_DIR="apps/game/.output/public"
CI="${CI:-}"
FORCE_SYNC_TERRAFORM="${FORCE_SYNC_TERRAFORM:-false}"
AWS_S3_BUCKET="${AWS_S3_BUCKET:-}"
AWS_CLOUDFRONT_ID="${AWS_CLOUDFRONT_ID:-}"
AWS_REGION="${AWS_REGION:-eu-central-1}"
SKIP_E2E_TESTS="${SKIP_E2E_TESTS:-false}"

# Get Terraform outputs (preferred) or use environment variables
echo -e "\n📋 Getting deployment configuration for ${ENVIRONMENT}..."

# Normalize environment name for Terraform directory
TERRAFORM_ENV=""
case "$ENVIRONMENT" in
    development|dev)
        TERRAFORM_ENV="development"
        ;;
    production|prod)
        TERRAFORM_ENV="prod"
        ;;
    *)
        TERRAFORM_ENV="$ENVIRONMENT"
        ;;
esac

TERRAFORM_DIR="infrastructure/environments/${TERRAFORM_ENV}"
TERRAFORM_ENV_FILE="${TERRAFORM_DIR}/.env.terraform"
TERRAFORM_JSON_FILE="${TERRAFORM_DIR}/terraform-outputs.json"

# For local deployments, sync Terraform outputs to JSON and .env files
if [ -z "$CI" ] && [ -d "$TERRAFORM_DIR" ] && command -v terraform &> /dev/null; then
    # Check if we should sync outputs (if files don't exist or are older than Terraform state)
    SYNC_NEEDED=false
    
    if [ ! -f "$TERRAFORM_ENV_FILE" ] || [ ! -f "$TERRAFORM_JSON_FILE" ]; then
        SYNC_NEEDED=true
    fi
    
    # Sync Terraform outputs to JSON and .env files
    if [ "$SYNC_NEEDED" = true ] || [ "${FORCE_SYNC_TERRAFORM}" = "true" ]; then
        echo -e "  ${BLUE}🔄 Syncing Terraform outputs to JSON and .env files...${NC}"
        if [ -f "scripts/sync-terraform-outputs.sh" ]; then
            bash scripts/sync-terraform-outputs.sh "$TERRAFORM_ENV" || {
                echo -e "  ${YELLOW}⚠️  Failed to sync Terraform outputs, continuing with direct Terraform queries${NC}"
            }
        else
            # Fallback: manually sync outputs
            cd "$TERRAFORM_DIR"
            
            # Initialize Terraform if needed
            if [ ! -d ".terraform" ]; then
                terraform init -backend=false 2>/dev/null || terraform init 2>/dev/null || {
                    cd - > /dev/null
                }
            fi
            
            # Export to JSON
            terraform output -json > terraform-outputs.json 2>/dev/null || true
            
            # Export to .env file
            cat > .env.terraform << EOF
# Terraform outputs for ${TERRAFORM_ENV} environment
# Auto-generated by aws-deploy.sh
# DO NOT EDIT MANUALLY - Run 'terraform apply' to update

AWS_S3_BUCKET=$(terraform output -raw bucket_name 2>/dev/null || echo "")
AWS_CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "eu-central-1")
CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")

# Environment-specific CloudFront domain
$(if [ "$TERRAFORM_ENV" = "prod" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")"
elif [ "$TERRAFORM_ENV" = "development" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN_DEV=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")"
fi)

# For Nuxt.js runtime config
NUXT_PUBLIC_CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
NUXT_PUBLIC_WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")
EOF
            
            cd - > /dev/null
            echo -e "  ${GREEN}✓${NC} Terraform outputs synced to ${TERRAFORM_ENV_FILE} and ${TERRAFORM_JSON_FILE}"
        fi
    fi
fi

# Load .env.terraform file if it exists (for local deployments)
if [ -f "$TERRAFORM_ENV_FILE" ]; then
    echo -e "  ${BLUE}📄 Loading Terraform outputs from .env file...${NC}"
    # Source the file to load variables
    set -a  # Automatically export all variables
    source "$TERRAFORM_ENV_FILE" 2>/dev/null || . "$TERRAFORM_ENV_FILE" 2>/dev/null || true
    set +a  # Disable automatic export
    echo -e "  ${GREEN}✓${NC} Loaded from ${TERRAFORM_ENV_FILE}"
fi

# Try to get Terraform outputs directly (as fallback or validation)
if [ -d "$TERRAFORM_DIR" ] && command -v terraform &> /dev/null; then
    cd "$TERRAFORM_DIR"
    
    # Initialize Terraform if needed
    if [ ! -d ".terraform" ]; then
        echo -e "  ${YELLOW}⚠️  Terraform not initialized. Initializing...${NC}"
        terraform init -backend=false 2>/dev/null || terraform init 2>/dev/null || {
            echo -e "  ${YELLOW}⚠️  Could not initialize Terraform, using environment variables${NC}"
            cd - > /dev/null
        }
    fi
    
    # Get Terraform outputs (validate or override .env file values)
    S3_BUCKET_FROM_TF=$(terraform output -raw bucket_name 2>/dev/null || echo "")
    CLOUDFRONT_ID_FROM_TF=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
    AWS_REGION_FROM_TF=$(terraform output -raw aws_region 2>/dev/null || echo "")
    CLOUDFRONT_DOMAIN_FROM_TF=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
    
    # Use Terraform outputs if available (they take precedence)
    if [ -n "$S3_BUCKET_FROM_TF" ]; then
        export AWS_S3_BUCKET="$S3_BUCKET_FROM_TF"
        echo -e "  ${GREEN}✓${NC} S3 Bucket from Terraform: $S3_BUCKET_FROM_TF"
    elif [ -z "$AWS_S3_BUCKET" ]; then
        echo -e "  ${YELLOW}⚠️  S3 bucket not found in Terraform outputs and AWS_S3_BUCKET not set${NC}"
        echo -e "  ${RED}❌ Cannot proceed without S3 bucket name${NC}"
        exit 1
    fi
    
    if [ -n "$CLOUDFRONT_ID_FROM_TF" ]; then
        export AWS_CLOUDFRONT_ID="$CLOUDFRONT_ID_FROM_TF"
        echo -e "  ${GREEN}✓${NC} CloudFront ID from Terraform: $CLOUDFRONT_ID_FROM_TF"
    elif [ -z "$AWS_CLOUDFRONT_ID" ]; then
        echo -e "  ${YELLOW}⚠️  CloudFront ID not found in Terraform outputs${NC}"
        echo -e "  ${YELLOW}   Cache invalidation will be skipped${NC}"
    fi
    
    if [ -n "$AWS_REGION_FROM_TF" ]; then
        export AWS_REGION="$AWS_REGION_FROM_TF"
        echo -e "  ${GREEN}✓${NC} AWS Region from Terraform: $AWS_REGION_FROM_TF"
    fi
    
    if [ -n "$CLOUDFRONT_DOMAIN_FROM_TF" ]; then
        # Set environment-specific variable
        if [ "$TERRAFORM_ENV" = "prod" ]; then
            export AWS_CLOUDFRONT_DOMAIN="$CLOUDFRONT_DOMAIN_FROM_TF"
        elif [ "$TERRAFORM_ENV" = "development" ]; then
            export AWS_CLOUDFRONT_DOMAIN_DEV="$CLOUDFRONT_DOMAIN_FROM_TF"
        fi
    fi
    
    cd - > /dev/null
else
    if [ ! -d "$TERRAFORM_DIR" ]; then
        echo -e "  ${YELLOW}⚠️  Terraform directory not found: $TERRAFORM_DIR${NC}"
    fi
    if ! command -v terraform &> /dev/null; then
        echo -e "  ${YELLOW}⚠️  Terraform not installed, using environment variables${NC}"
    fi
    if [ -z "$AWS_S3_BUCKET" ]; then
        echo -e "  ${YELLOW}   Using environment variables for deployment configuration${NC}"
    fi
fi

# Validate required variables
if [ -z "$AWS_S3_BUCKET" ]; then
    echo -e "${RED}❌ AWS_S3_BUCKET is required but not set${NC}"
    echo -e "${YELLOW}   Set it as an environment variable or run 'terraform apply' in ${TERRAFORM_DIR}${NC}"
    exit 1
fi

# Use validated variables
S3_BUCKET="$AWS_S3_BUCKET"
CLOUDFRONT_ID="${AWS_CLOUDFRONT_ID:-}"
AWS_REGION="${AWS_REGION:-eu-central-1}"

echo -e "${BLUE}🚀 Starting AWS deployment for ${ENVIRONMENT}...${NC}"
echo "======================================="

require_cmd aws

# Check AWS credentials
echo -e "\n🔑 Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}❌ AWS credentials not configured. Please run 'aws configure'${NC}"
    exit 1
fi

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
AWS_USER=$(aws sts get-caller-identity --query Arn --output text | cut -d'/' -f2)
echo -e "${GREEN}✓ AWS CLI configured${NC}"
echo -e "  Account: ${AWS_ACCOUNT}"
echo -e "  User: ${AWS_USER}"

# Pre-deployment checks (skip in CI if already done)
if [ -z "$CI" ]; then
  echo -e "\n🔍 Running pre-deployment checks..."

  echo -e "\n📦 Installing dependencies..."
  ensure_pnpm
  pnpm install --frozen-lockfile

  echo -e "\n✅ Running linter..."
  (cd apps/game && pnpm run lint) || { echo -e "${RED}❌ Lint failed${NC}"; exit 1; }

  echo -e "\n🔷 Running type check..."
  (cd apps/game && pnpm run typecheck) || { echo -e "${RED}❌ Type check failed${NC}"; exit 1; }

  echo -e "\n🧪 Running unit tests..."
  (cd apps/game && pnpm run test:unit) || { echo -e "${RED}❌ Tests failed${NC}"; exit 1; }

  echo -e "${GREEN}✓ All pre-deployment checks passed${NC}"

  # Build the application
  echo -e "\n🏗️  Building application..."
  pnpm -C apps/game run generate
else
  echo -e "\n⏭️  Skipping pre-deployment checks (already done in CI pipeline)"
  echo -e "\n⏭️  Using existing build from CI pipeline"
fi

if [ ! -d "$BUILD_DIR" ]; then
    echo -e "${RED}❌ Build directory not found: $BUILD_DIR${NC}"
    exit 1
fi

if [ -z "$CI" ]; then
  echo -e "${GREEN}✓ Build completed${NC}"
fi

# Verify build output
FILE_COUNT=$(find "$BUILD_DIR" -type f | wc -l)
echo -e "  Files generated: ${FILE_COUNT}"

# Check if S3 bucket exists
echo -e "\n🪣 Checking S3 bucket: ${S3_BUCKET}..."
if ! aws s3 ls "s3://$S3_BUCKET" 2>&1 > /dev/null; then
    echo -e "${YELLOW}⚠️  Bucket doesn't exist. Creating...${NC}"

    # Create bucket
    if [ "$AWS_REGION" = "us-east-1" ]; then
        aws s3 mb "s3://$S3_BUCKET"
    else
        aws s3 mb "s3://$S3_BUCKET" --region "$AWS_REGION"
    fi

    # Configure bucket for static website hosting
    aws s3 website "s3://$S3_BUCKET" \
        --index-document index.html \
        --error-document 404.html

    # Set bucket policy for public read access
    BUCKET_POLICY_FILE="$(mktemp)"
    cat > "${BUCKET_POLICY_FILE}" <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::${S3_BUCKET}/*"
        }
    ]
}
EOF

    aws s3api put-bucket-policy --bucket "$S3_BUCKET" --policy "file://${BUCKET_POLICY_FILE}"
    rm -f "${BUCKET_POLICY_FILE}"

    # Disable block public access (required for static website hosting)
    aws s3api put-public-access-block \
        --bucket "$S3_BUCKET" \
        --public-access-block-configuration \
        "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

    echo -e "${GREEN}✓ Bucket created and configured for static website hosting${NC}"
else
    echo -e "${GREEN}✓ Bucket exists${NC}"
fi

# Upload to S3 with optimized caching
echo -e "\n☁️  Uploading to S3..."

# Upload static assets with long-term caching (1 year)
echo -e "  Uploading static assets (CSS, JS, images)..."
aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" \
    --delete \
    --cache-control "public, max-age=31536000, immutable" \
    --exclude "*.html" \
    --exclude "sw.js" \
    --exclude "workbox-*.js" \
    --exclude "manifest.json" \
    --exclude "*.xml" \
    --exclude "*.txt"

# Upload HTML files and service worker with no-cache
echo -e "  Uploading HTML files and service worker..."
aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" \
    --cache-control "public, max-age=0, must-revalidate" \
    --exclude "*" \
    --include "*.html" \
    --content-type "text/html; charset=utf-8"

# Upload service worker files with no-cache
aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" \
    --cache-control "public, max-age=0, must-revalidate" \
    --exclude "*" \
    --include "sw.js" \
    --include "workbox-*.js" \
    --content-type "application/javascript; charset=utf-8"

# Upload manifest and other special files
aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" \
    --cache-control "public, max-age=86400" \
    --exclude "*" \
    --include "manifest.json" \
    --include "*.xml" \
    --include "robots.txt"

echo -e "${GREEN}✓ Files uploaded to S3${NC}"

# Get upload stats
TOTAL_SIZE=$(du -sh "$BUILD_DIR" | cut -f1)
echo -e "  Total size: ${TOTAL_SIZE}"

# Invalidate CloudFront cache if distribution ID is provided
if [ -n "$CLOUDFRONT_ID" ]; then
    echo -e "\n🔄 Invalidating CloudFront cache..."
    INVALIDATION_ID=$(aws cloudfront create-invalidation \
        --distribution-id "$CLOUDFRONT_ID" \
        --paths "/*" \
        --query 'Invalidation.Id' \
        --output text)
    echo -e "${GREEN}✓ CloudFront cache invalidated (ID: ${INVALIDATION_ID})${NC}"
    echo -e "  Note: Invalidation may take 5-15 minutes to complete"
else
    echo -e "${YELLOW}⚠️  No CloudFront distribution ID provided. Skipping cache invalidation.${NC}"
    echo -e "${YELLOW}  Set AWS_CLOUDFRONT_ID environment variable to enable this.${NC}"
fi

# Display deployment URLs
echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🎉 Deployment complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [ -n "$CLOUDFRONT_ID" ]; then
    CF_DOMAIN=$(aws cloudfront get-distribution --id "$CLOUDFRONT_ID" --query 'Distribution.DomainName' --output text)
    echo -e "\n${BLUE}CloudFront URL:${NC}"
    echo -e "  ${GREEN}https://$CF_DOMAIN${NC}"
else
    echo -e "\n${BLUE}S3 Website URL:${NC}"
    echo -e "  ${GREEN}http://$S3_BUCKET.s3-website-$AWS_REGION.amazonaws.com${NC}"
fi

# Show additional recommendations
echo -e "\n${YELLOW}📋 Production Checklist:${NC}"
if [ -z "$CLOUDFRONT_ID" ]; then
    echo -e "  ${YELLOW}□${NC} Set up CloudFront distribution for HTTPS and better performance"
fi
echo -e "  ${YELLOW}□${NC} Configure custom domain with Route 53"
echo -e "  ${YELLOW}□${NC} Add SSL certificate from ACM"
echo -e "  ${YELLOW}□${NC} Configure security headers (CSP, HSTS, etc.)"
echo -e "  ${YELLOW}□${NC} Set up monitoring and alerts (CloudWatch)"
echo -e "  ${YELLOW}□${NC} Configure WAF rules if needed"

echo -e "\n${BLUE}Deployment log saved to: deployment-$(date +%Y%m%d-%H%M%S).log${NC}"

# Save deployment metadata
cat > deployment-info.json <<EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "environment": "$ENVIRONMENT",
  "bucket": "$S3_BUCKET",
  "region": "$AWS_REGION",
  "cloudfrontId": "$CLOUDFRONT_ID",
  "deployedBy": "$AWS_USER",
  "buildSize": "$TOTAL_SIZE",
  "fileCount": $FILE_COUNT
}
EOF

# Run E2E tests against deployed site (only for local deployments, not CI)
if [ -z "$CI" ] && [ -n "$CLOUDFRONT_ID" ] && [ "${SKIP_E2E_TESTS}" != "true" ]; then
    echo -e "\n🧪 Running E2E tests against deployed site..."
    
    # Get CloudFront domain
    CF_DOMAIN=$(aws cloudfront get-distribution --id "$CLOUDFRONT_ID" --query 'Distribution.DomainName' --output text)
    DEPLOYED_URL="https://$CF_DOMAIN"
    
    echo -e "  Testing URL: ${DEPLOYED_URL}"
    
    # First, verify the site is accessible
    echo -e "  Checking if site is reachable..."
    require_cmd curl
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$DEPLOYED_URL" || echo "000")
    
    if [ "$HTTP_CODE" != "200" ] && [ "$HTTP_CODE" != "301" ] && [ "$HTTP_CODE" != "302" ]; then
        echo -e "${RED}❌ Site returned HTTP $HTTP_CODE - deployment may have failed${NC}"
        echo -e "${YELLOW}⚠️  Please check:${NC}"
        echo -e "${YELLOW}  1. CloudFront distribution status${NC}"
        echo -e "${YELLOW}  2. S3 bucket permissions${NC}"
        echo -e "${YELLOW}  3. CloudFront Origin Access Control configuration${NC}"
        echo -e "${YELLOW}  Skipping E2E tests due to deployment verification failure${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Site is reachable (HTTP $HTTP_CODE)${NC}"
    echo -e "  Waiting 15 seconds for CloudFront cache invalidation to propagate..."
    sleep 15
    
    # Check if Playwright is available
    if command -v pnpm &> /dev/null && [ -d "apps/game" ]; then
        # Run E2E tests against the deployed site
        echo -e "  Running Playwright E2E tests..."
        if BASE_URL="$DEPLOYED_URL" pnpm -C apps/game exec playwright test --reporter=list; then
            echo -e "${GREEN}✓ E2E tests passed${NC}"
        else
            echo -e "${RED}❌ E2E tests failed${NC}"
            echo -e "${YELLOW}⚠️  Deployment completed but E2E tests failed. Please investigate.${NC}"
            echo -e "${YELLOW}  View test report: apps/game/playwright-report/index.html${NC}"
            exit 1
        fi
    else
        echo -e "${YELLOW}⚠️  Playwright not available. Skipping E2E tests.${NC}"
        echo -e "${YELLOW}  Install with: pnpm install${NC}"
    fi
elif [ -z "$CI" ] && [ -z "$CLOUDFRONT_ID" ]; then
    echo -e "\n${YELLOW}⚠️  No CloudFront ID provided. Skipping E2E tests.${NC}"
    echo -e "${YELLOW}  Set AWS_CLOUDFRONT_ID to enable E2E test verification.${NC}"
elif [ "${SKIP_E2E_TESTS:-false}" == "true" ]; then
    echo -e "\n⏭️  Skipping E2E tests (SKIP_E2E_TESTS=true)${NC}"
else
    echo -e "\n⏭️  Skipping E2E tests (running in CI - use verify:e2e:aws:* jobs)${NC}"
fi

echo -e "\n${GREEN}✅ Done!${NC}"
