tap "ajrosen/tap"
tap "amjaradat01/awesome-lazy-zsh"
tap "anomalyco/tap"
tap "antoniorodr/memo"
tap "asmvik/formulae"
tap "badabing2005/pixelflasher"
tap "catalpainternational/catalpa"
tap "cecilapp/tap"
tap "charmbracelet/tap"
tap "coder/coder"
tap "dracula/install"
tap "hashicorp/tap"
tap "j-x-z/tap"
tap "jandedobbeleer/oh-my-posh"
tap "joseluisq/paket"
tap "keisukeyamashita/tap"
tap "kepkin/kongctl"
tap "kilo-org/tap"
tap "lightbend/brew"
tap "lizardbyte/homebrew"
tap "marema31/marema31"
tap "mikedan37/daemon-inspector"
tap "misha-ssh/tap"
tap "mkdika/brew"
tap "mkpkg/taps"
tap "openhue/cli"
tap "ovh/tap"
tap "proffapt/brewtap"
tap "rafaelswi/menubarusb"
tap "raystack/tap"
tap "spring-io/tap"
tap "steipete/tap"
tap "whatpulse/whatpulse"
tap "xavier7179/research_libs"
tap "yakitrak/yakitrak"
brew "actionlint"
brew "openssl@3"
brew "readline"
brew "xz"
brew "zstd"
brew "agent-browser"
brew "air"
brew "airspy"
brew "amp"
brew "ansible"
brew "apkleaks"
brew "gcc"
brew "gnupg"
brew "pkgconf"
brew "imagemagick"
brew "libb2"
brew "appium"
brew "asdf"
brew "astroterm"
brew "aws-shell"
brew "awscli"
brew "awslogs"
brew "bash"
brew "bash-completion@2"
brew "bash-language-server"
brew "bat"
brew "bitwarden-cli"
brew "blueutil"
brew "boom-completion"
brew "brew-cask-completion"
brew "bwidget"
brew "cake"
brew "cava"
brew "chainhook"
brew "circleci"
brew "claude-agent-acp"
brew "claude-cmd"
brew "claude-code-router"
brew "claude-code-templates"
brew "claude-squad"
brew "claudekit"
brew "clipboard"
brew "cloudflared", restart_service: :changed
brew "cobo-cli"
brew "code-cli"
brew "code-server"
brew "codeberg-cli"
brew "coreutils"
brew "dash-shell"
brew "dependabot"
brew "dosfstools"
brew "eza"
brew "ffmpeg"
brew "fish"
brew "fizsh"
brew "fzf"
brew "fzy"
brew "gemini-cli"
brew "gh"
brew "ghostscript"
brew "git-lfs"
brew "glab"
brew "goenv"
brew "graphviz"
brew "hadolint"
brew "htop"
brew "ironclaw"
brew "jq"
brew "jupyterlab"
brew "llvm"
brew "lld"
brew "lrzsz"
brew "lsd"
brew "lume"
brew "neofetch"
brew "ninja"
brew "notmuch"
brew "nowplaying-cli"
brew "nvm"
brew "openai-whisper"
brew "openclaw-cli"
brew "opencode"
brew "optipng"
brew "partio"
brew "pass"
brew "peco"
brew "php"
brew "pieces-cli"
brew "pinentry-mac"
brew "pyenv"
brew "pyenv-virtualenv"
brew "qemu"
brew "rbenv"
brew "rclone"
brew "sonic", restart_service: :changed
brew "spot"
brew "spotifyd", restart_service: :changed
brew "starship"
brew "subversion"
brew "summarize"
brew "tcl-tk@8"
brew "tcsh"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "tin"
brew "tmux"
brew "uutils-findutils"
brew "uv"
brew "vercel-cli"
brew "zeroclaw"
brew "zlib"
brew "zsh-async"
brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "zsh-lovers"
brew "zsh-syntax-highlighting"
brew "zsh-system-clipboard"
brew "zshdb"
brew "ajrosen/tap/bitwarden-accelerator"
brew "amjaradat01/awesome-lazy-zsh/awesome-lazy-zsh"
brew "antoniorodr/memo/memo"
brew "asmvik/formulae/skhd"
brew "cecilapp/tap/cecil"
brew "charmbracelet/tap/crush"
brew "coder/coder/coder"
brew "j-x-z/tap/cocoa-way"
brew "j-x-z/tap/waypipe-darwin"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "joseluisq/paket/paket-bin"
brew "lizardbyte/homebrew/sunshine"
brew "openhue/cli/openhue-cli"
brew "raystack/tap/guardian"
brew "raystack/tap/meteor"
brew "raystack/tap/optimus"
brew "spring-io/tap/spring-boot"
brew "steipete/tap/gogcli"
brew "steipete/tap/goplaces"
brew "steipete/tap/ordercli"
brew "steipete/tap/peekaboo"
brew "steipete/tap/remindctl"
brew "yakitrak/yakitrak/obsidian-cli"
cask "a-better-finder-attributes"
cask "activedock"
cask "adobe-creative-cloud"
cask "affinity"
cask "ai-studio"
cask "aionui"
cask "airbuddy"
cask "airdroid"
cask "akiflow"
cask "alcove"
cask "aldente"
cask "alfred"
cask "alt-tab"
cask "altserver"
cask "android-file-transfer"
cask "android-platform-tools"
cask "androidtool"
cask "anki"
cask "antigravity"
cask "antinote"
cask "anybar"
cask "anydesk"
cask "applite"
cask "arc"
cask "babeledit"
cask "bartender"
cask "battle-net"
cask "bazecor"
cask "bbedit"
cask "betterdiscord-installer"
cask "bettershot"
cask "beyond-compare"
cask "bitwarden"
cask "bitwig-studio"
cask "blisk"
cask "block-goose"
cask "bloom"
cask "bluebubbles"
cask "bookmacster"
cask "brave-browser"
cask "brewlet"
cask "browseros"
cask "butler"
cask "cakebrewjs"
cask "captains-deck"
cask "chatgpt-atlas"
cask "cherry-studio"
cask "claude"
cask "cloudflare-warp"
cask "coconutbattery"
cask "codebuddy"
cask "codeedit"
cask "coder/coder/coder-desktop"
cask "codex"
cask "codex-app"
cask "steipete/tap/codexbar"
cask "cog-app"
cask "coherence-x"
cask "colorwell"
cask "comet"
cask "copilot-cli"
cask "core-tunnel"
cask "cork"
cask "coteditor"
cask "crossover"
cask "cursor"
cask "cursor-cli"
cask "customshortcuts"
cask "daisydisk"
cask "dash"
cask "dbeaver-community"
cask "devutils"
cask "discord"
cask "dockdoor"
cask "docker-desktop"
cask "dockflow"
cask "dockview"
cask "dolphin"
cask "dracula/install/dracula-betterdiscord"
cask "dracula/install/dracula-gitkraken"
cask "duckduckgo"
cask "emojipedia"
cask "epic-games"
cask "ferdium"
cask "figma"
cask "finetune"
cask "firefox"
cask "foobar2000"
cask "forklift"
cask "gcloud-cli"
cask "geekbench"
cask "genymotion"
cask "ghost-browser"
cask "ghostty"
cask "git-credential-manager"
cask "github"
cask "gitkraken"
cask "google-chrome"
cask "google-chrome@canary"
cask "gpgfrontend"
cask "handy"
cask "hashicorp/tap/hashicorp-vagrant"
cask "hazel"
cask "hazeover"
cask "hype"
cask "hyper"
cask "hyperconnect"
cask "hyperkey"
cask "iina"
cask "itermai"
cask "itsycal"
cask "jan"
cask "jellyfin-media-player"
cask "jetbrains-toolbox"
cask "jettison"
cask "jordanbaird-ice"
cask "keep-it"
cask "keyclu"
cask "kiro"
cask "kiro-cli"
cask "kitty"
cask "kodi"
cask "langflow"
cask "lasso-app"
cask "latest"
cask "launchbar"
cask "launchcontrol"
cask "league-of-legends"
cask "libndi"
cask "lm-studio"
cask "logseq"
cask "maccy"
cask "macdroid"
cask "macforge"
cask "macgamestore"
cask "macpilot"
cask "macpulse"
cask "macupdater"
cask "media-center"
cask "rafaelswi/menubarusb/menubarusb"
cask "menubarx"
cask "meta"
cask "microsoft-edge"
cask "misha-ssh/tap/misha"
cask "monitorcontrol"
cask "moom"
cask "multitouch"
cask "music-widget"
cask "mweb-pro"
cask "neo-network-utility"
cask "neofinder"
cask "ngrok"
cask "nimble-commander"
cask "notebooks"
cask "notion"
cask "notion-calendar"
cask "notion-enhanced"
cask "nova"
cask "nvidia-geforce-now"
cask "obsidian"
cask "ollama-app"
cask "omnidisksweeper"
cask "omniplan"
cask "only-switch"
cask "openclaw"
cask "opencloud"
cask "openinterminal"
cask "opera-air"
cask "opera-gx"
cask "orbstack"
cask "orion"
cask "ovh/tap/ovhcloud-cli"
cask "parallels"
cask "pastebot"
cask "path-finder"
cask "pearcleaner"
cask "pieces-os"
cask "badabing2005/pixelflasher/pixelflasher"
cask "podman-desktop"
cask "privadovpn"
cask "proxyman"
cask "quicksilver"
cask "raindropio"
cask "rapidapi"
cask "raspberry-pi-imager"
cask "raycast"
cask "rclone-ui"
cask "rectangle"
cask "repo-prompt"
cask "responsively"
cask "runjs"
cask "rustdesk"
cask "sensei"
cask "setapp"
cask "shottr"
cask "singlebox"
cask "slack"
cask "slack-cli"
cask "sofa-server"
cask "soulseek"
cask "soundsource"
cask "spacedrive"
cask "spotify"
cask "spotify-now-playing"
cask "spotmenu"
cask "squidman"
cask "ssh-config-editor"
cask "stats"
cask "sublime-merge"
cask "sublime-text"
cask "swinsian"
cask "switchhosts"
cask "tabby"
cask "telegram"
cask "termius"
cask "textmate"
cask "thaw"
cask "thebrowsercompany-dia"
cask "tiles"
cask "tinymediamanager"
cask "todoist-app"
cask "tor-browser"
cask "trae"
cask "trunk-io"
cask "tunnelbear"
cask "turbovnc-viewer"
cask "tyme"
cask "ui-tars"
cask "ungoogled-chromium"
cask "unified-remote"
cask "utm"
cask "vanilla"
cask "vibe-notch"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "vnc-viewer"
cask "vscodium"
cask "warp"
cask "wave"
cask "webcatalog"
cask "webstorm"
cask "wezterm"
cask "whatpulse/whatpulse/whatpulse"
cask "whatpulse/whatpulse/whatpulse_chmodbpf"
cask "whatsapp"
cask "windsurf"
cask "wispr-flow"
cask "xcodes-app"
cask "yam-display"
cask "yoink"
cask "zed"
cask "zotero"
mas "Actions", id: 1586435171
mas "ApolloOne", id: 1044484672
mas "AppIconBuilder", id: 1294179975
mas "Apple Configurator", id: 1037126344
mas "Boop", id: 1518425043
mas "Cake Wallet", id: 1334702542
mas "CardPointers", id: 1472875808
mas "Code AI", id: 6446805484
mas "Codye", id: 1516894961
mas "Color Widgets", id: 1531594277
mas "Core Tunnel", id: 1354318707
mas "DaftCloud", id: 1320450034
mas "Developer", id: 640199958
mas "DevHub", id: 6476452351
mas "EaseUS Partition Master", id: 6739610996
mas "FileZilla Pro", id: 1298486723
mas "Flighty", id: 1358823008
mas "Flow 2", id: 1423210932
mas "GarageBand", id: 682658836
mas "Instapaper", id: 288545208
mas "Keynote", id: 409183694
mas "LimeChat", id: 414030210
mas "Liquid", id: 569048352
mas "Localisation Assistant", id: 6449604219
mas "Lunatask", id: 1583719331
mas "MacDroid", id: 1476545828
mas "MindNode", id: 6446116532
mas "Mockup", id: 1527554407
mas "Momentum", id: 1564329434
mas "Motrix", id: 6447776319
mas "Nimble Commander", id: 905202937
mas "Notability", id: 360593530
mas "Notion Web Clipper", id: 1559269364
mas "Octotree", id: 1457450145
mas "OmniFocus", id: 1542143627
mas "Outbank", id: 1094255754
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "PiPifier", id: 1160374471
mas "Prime Video", id: 545519333
mas "Prompt", id: 1594420480
mas "QuickDrop", id: 6740147178
mas "Refined GitHub", id: 1519867270
mas "RocketSim", id: 1504940162
mas "Shareful", id: 1522267256
mas "Shazam", id: 897118787
mas "Shortery", id: 1594183810
mas "SimplyCodes", id: 1538885494
mas "SnippetsLab", id: 1006087419
mas "Snippit", id: 1465481124
mas "Spaced", id: 1666327168
mas "Spark Desktop", id: 6445813049
mas "Speedtest", id: 1153157709
mas "Steam Link", id: 1246969117
mas "superagent", id: 1568262835
mas "Swift Playground", id: 1496833156
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Today", id: 6443714928
mas "Toggl Track", id: 1291898086
mas "Tot", id: 1491071483
mas "Transporter", id: 1450874784
mas "Trello", id: 1278508951
mas "uBlock Origin Lite", id: 6745342698
mas "Userscripts", id: 1463298887
mas "Xcode", id: 497799835
vscode "\e[2m[2026-04-26 07:20:48]\e[0m \e[31merror\e[0m error running editor from /opt/homebrew/bin/code: resource temporarily unavailable (os error 35)"
go "github.com/poloxue/modv"
go "moul.io/pkgman"
go "github.com/browserbase/stagehand-cli/cmd/stagehand"
uv "-"
uv "-"
uv "aider-chat", with: ["pip"]
uv "batrachian-toad"
uv "bauh"
uv "codegen"
uv "crewai"
uv "fastmcp"
uv "kimi-cli"
uv "mistral-vibe"
uv "nano-pdf"
uv "openhands"
