# GitLab CI configuration for building and publishing custom Docker image
# This pipeline builds the CI Docker image and pushes it to GitLab Container Registry
# Run this pipeline manually when dependencies change to update the cached image

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/ci-build
  DOCKER_IMAGE_TAG: latest

stages:
  - build
  - publish

build-ci-image:
  stage: build
  image: docker:27-cli
  services:
    - docker:27-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - |
      echo "Building Docker image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      docker build \
        -f .gitlab/Dockerfile.ci \
        -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" \
        -t "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
        .
    - |
      echo "Pushing Docker image to registry"
      docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      docker push "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - |
      echo "Docker image published successfully!"
      echo "Image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      echo "Image: $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /\[build-docker\]/
      when: always
    - when: never
  tags:
    - docker

verify-ci-image:
  stage: publish
  image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  script:
    - node --version
    - pnpm --version
    - git --version
    - |
      echo "Verifying pre-installed dependencies..."
      if [ -d "node_modules" ]; then
        echo "✓ node_modules directory exists"
      else
        echo "✗ node_modules directory missing"
        exit 1
      fi
  dependencies:
    - build-ci-image
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /\[build-docker\]/
      when: always
    - when: never
