# Lambda SSR Module for Nuxt/Nitro
# Deploys the Nuxt SSR application as AWS Lambda + API Gateway

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
}

variable "environment" {
  description = "Environment (development/staging/production)"
  type        = string
}

variable "lambda_zip_path" {
  description = "Path to the Lambda deployment package (generated by Nitro)"
  type        = string
}

variable "lambda_runtime" {
  description = "Node.js runtime for Lambda"
  type        = string
  default     = "nodejs22.x"
}

variable "lambda_memory" {
  description = "Memory allocation for Lambda function (MB)"
  type        = number
  default     = 512
}

variable "lambda_timeout" {
  description = "Timeout for Lambda function (seconds)"
  type        = number
  default     = 10
}

variable "domain_name" {
  description = "Custom domain name for API Gateway (optional)"
  type        = string
  default     = ""
}

variable "certificate_arn" {
  description = "ACM certificate ARN for custom domain (required if domain_name is set)"
  type        = string
  default     = ""
}

variable "tags" {
  description = "Additional tags for resources"
  type        = map(string)
  default     = {}
}
