services:
  server:
    image: codeberg.org/crowci/crow-server:<version>
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - cro-data:/var/lib/crow
    environment:
      - CROW_OPEN=true
      - CROW_HOST=http://localhost:8000
      - CROW_AGENT_SECRET=your-agent-secret
      - CROW_FORGEJO=true
      - CROW_FORGEJO_URL=https://codeberg.org
      - CROW_FORGEJO_CLIENT=your-oauth-client-id
      - CROW_FORGEJO_SECRET=your-oauth-client-secret

  agent:
    image: codeberg.org/crowci/crow-agent:<version>
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CROW_SERVER=server:9000
      - CROW_AGENT_SECRET=your-agent-secret

volumes:
  crow-data:
