#!/bin/bash

# Mistral Vibe Integration Setup Script
# Sets up the enhanced MCP configuration for Mistral Vibe

echo "🚀 Setting up Mistral Vibe integration..."

# Create Vibe config directory
VIBE_DIR="$HOME/.vibe"
echo "📁 Creating Vibe config directory: $VIBE_DIR"
mkdir -p "$VIBE_DIR"

# Copy MCP configuration
REPO_ROOT=$(dirname "$(dirname "$0")")
MCP_CONFIG="$REPO_ROOT/vibe-mcp-enhanced.json"

if [ -f "$MCP_CONFIG" ]; then
    echo "📋 Copying MCP configuration..."
    cp "$MCP_CONFIG" "$VIBE_DIR/mcp-config.json"
    echo "✅ MCP configuration copied to $VIBE_DIR/mcp-config.json"
else
    echo "❌ MCP configuration not found at $MCP_CONFIG"
    echo "Please run the export script first: node scripts/export-mcp-enhanced.js"
    exit 1
fi

# Create or update config.toml
CONFIG_FILE="$VIBE_DIR/config.toml"
echo "📝 Setting up Vibe configuration..."

if [ -f "$CONFIG_FILE" ]; then
    # Check if MCP section already exists
    if grep -q "\[mcp\]" "$CONFIG_FILE"; then
        echo "ℹ️  MCP section already exists in config.toml"
        echo "    You may want to update it manually:"
        echo "    [mcp]"
        echo "    config_path = \"$VIBE_DIR/mcp-config.json\""
    else
        echo "📝 Adding MCP section to existing config.toml"
        cat >> "$CONFIG_FILE" << 'EOF'

[mcp]
config_path = "~/.vibe/mcp-config.json"
EOF
    fi
else
    echo "📝 Creating new config.toml with MCP configuration"
    cat > "$CONFIG_FILE" << 'EOF'
# Mistral Vibe Configuration
# Generated by Riddle Rush MCP Export System

[mcp]
config_path = "~/.vibe/mcp-config.json"

# Additional Vibe settings can be added here
# [agent]
# model = "devstral-3"
# temperature = 0.7
EOF
fi

echo "✅ Vibe configuration updated: $CONFIG_FILE"

# Verify the setup
echo "\n🔍 Verification:"
echo "  MCP Config: $VIBE_DIR/mcp-config.json"
if [ -f "$VIBE_DIR/mcp-config.json" ]; then
    echo "    ✅ Found ($(wc -l < "$VIBE_DIR/mcp-config.json") lines)"
else
    echo "    ❌ Not found"
fi

echo "  Vibe Config: $CONFIG_FILE"
if [ -f "$CONFIG_FILE" ]; then
    echo "    ✅ Found"
    if grep -q "\[mcp\]" "$CONFIG_FILE"; then
        echo "    ✅ MCP section configured"
    else
        echo "    ⚠️  MCP section not found"
    fi
else
    echo "    ❌ Not found"
fi

echo "\n🎉 Mistral Vibe integration setup complete!"
echo ""
echo "Next steps:"
echo "  1. Restart your Mistral Vibe agent"
echo "  2. Verify MCP servers are available:"
echo "     vibe list-servers"
echo "  3. Use the integrated servers in your workflows"
echo ""
echo "Documentation:"
echo "  • Full guide: ENHANCED-MCP-EXPORT-GUIDE.md"
echo "  • Integration: $CONFIG_FILE"
echo "  • MCP Config: $VIBE_DIR/mcp-config.json"
