#!/usr/bin/env bash

# Script to sync Terraform outputs to JSON files and environment variables
# This makes Terraform outputs available to Nuxt.js and deployment scripts

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"
ensure_repo_root

ENVIRONMENT="${1:-prod}"
INFRA_DIR="infrastructure/environments/${ENVIRONMENT}"
log "${BLUE}🔄 Syncing Terraform outputs for ${ENVIRONMENT}...${NC}"

# Check if directory exists
if [ ! -d "$INFRA_DIR" ]; then
    die "Environment directory not found: ${INFRA_DIR}"
fi

# Check if terraform is available
require_cmd terraform

# Navigate to environment directory
cd "$INFRA_DIR"

# Check if initialized
if [ ! -d ".terraform" ]; then
    log "${YELLOW}⚠️  Terraform not initialized. Running init...${NC}"
    terraform init
fi

# Check if Terraform has been applied
if ! terraform output -json > /dev/null 2>&1; then
    die "No Terraform outputs found. Run 'terraform apply' first"
fi

# Export outputs to JSON file
log "${BLUE}Exporting outputs to JSON...${NC}"
terraform output -json > terraform-outputs.json || {
    die "Failed to export Terraform outputs to JSON"
}
log "  ${GREEN}✓${NC} Exported to terraform-outputs.json"

# Get all output values
BUCKET_NAME=$(terraform output -raw bucket_name 2>/dev/null || echo "")
BUCKET_ARN=$(terraform output -raw bucket_arn 2>/dev/null || echo "")
CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "eu-central-1")
WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")
DEPLOY_COMMAND=$(terraform output -raw deploy_command 2>/dev/null || echo "")

# Create .env file with all outputs
log "${BLUE}Creating .env file...${NC}"
cat > .env.terraform << EOF
# Terraform outputs for ${ENVIRONMENT} environment
# Generated by sync-terraform-outputs.sh
# DO NOT EDIT MANUALLY - This file is auto-generated
# To update: Run 'terraform apply' then 'scripts/sync-terraform-outputs.sh ${ENVIRONMENT}'

# Required deployment variables
AWS_S3_BUCKET=${BUCKET_NAME}
AWS_CLOUDFRONT_ID=${CLOUDFRONT_ID}
AWS_REGION=${AWS_REGION}

# CloudFront configuration
CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
WEBSITE_URL=${WEBSITE_URL}

# S3 bucket information
AWS_S3_BUCKET_ARN=${BUCKET_ARN}

# Environment-specific CloudFront domain variables
# For production: AWS_CLOUDFRONT_DOMAIN
# For development: AWS_CLOUDFRONT_DOMAIN_DEV
# For staging: AWS_CLOUDFRONT_DOMAIN_STAGING
$(if [ "$ENVIRONMENT" = "prod" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}"
elif [ "$ENVIRONMENT" = "development" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN_DEV=${CLOUDFRONT_DOMAIN}"
elif [ "$ENVIRONMENT" = "staging" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN_STAGING=${CLOUDFRONT_DOMAIN}"
fi)

# For Nuxt.js runtime config
NUXT_PUBLIC_CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
NUXT_PUBLIC_WEBSITE_URL=${WEBSITE_URL}

# Deployment command (for reference)
# DEPLOY_COMMAND=${DEPLOY_COMMAND}
EOF

# Validate that required outputs are present
if [ -z "$BUCKET_NAME" ]; then
    warn "S3 bucket name not found in Terraform outputs"
fi

if [ -z "$CLOUDFRONT_ID" ]; then
    warn "CloudFront distribution ID not found in Terraform outputs"
fi

if [ -z "$CLOUDFRONT_DOMAIN" ]; then
    warn "CloudFront domain name not found in Terraform outputs"
fi

# Go back to project root
cd - > /dev/null

log "\n${GREEN}✅ Terraform outputs synced!${NC}"
log "${BLUE}Files created:${NC}"
log "  - ${INFRA_DIR}/terraform-outputs.json"
log "  - ${INFRA_DIR}/.env.terraform"
log ""
log "${BLUE}💡 To use in Nuxt.js:${NC}"
log "  ${YELLOW}source ${INFRA_DIR}/.env.terraform${NC}"
log ""
log "${BLUE}💡 To use in deployment:${NC}"
log "  ${YELLOW}source ${INFRA_DIR}/.env.terraform && ./aws-deploy.sh ${ENVIRONMENT}${NC}"
