#!/bin/bash

# Script to sync Terraform outputs to JSON files and environment variables
# This makes Terraform outputs available to Nuxt.js and deployment scripts

set -e

ENVIRONMENT="${1:-prod}"
INFRA_DIR="infrastructure/environments/${ENVIRONMENT}"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔄 Syncing Terraform outputs for ${ENVIRONMENT}...${NC}"

# Check if directory exists
if [ ! -d "$INFRA_DIR" ]; then
    echo -e "${RED}❌ Environment directory not found: ${INFRA_DIR}${NC}"
    exit 1
fi

# Check if terraform is available
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform not found. Run 'pnpm run infra:setup' first${NC}"
    exit 1
fi

# Navigate to environment directory
cd "$INFRA_DIR"

# Check if initialized
if [ ! -d ".terraform" ]; then
    echo -e "${YELLOW}⚠️  Terraform not initialized. Running init...${NC}"
    terraform init
fi

# Check if Terraform has been applied
if ! terraform output -json > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  No Terraform outputs found. Run 'terraform apply' first${NC}"
    exit 1
fi

# Export outputs to JSON file
echo -e "${BLUE}Exporting outputs to JSON...${NC}"
terraform output -json > terraform-outputs.json || {
    echo -e "${RED}❌ Failed to export Terraform outputs to JSON${NC}"
    exit 1
}
echo -e "  ${GREEN}✓${NC} Exported to terraform-outputs.json"

# Get all output values
BUCKET_NAME=$(terraform output -raw bucket_name 2>/dev/null || echo "")
BUCKET_ARN=$(terraform output -raw bucket_arn 2>/dev/null || echo "")
CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "eu-central-1")
WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")
DEPLOY_COMMAND=$(terraform output -raw deploy_command 2>/dev/null || echo "")

# Create .env file with all outputs
echo -e "${BLUE}Creating .env file...${NC}"
cat > .env.terraform << EOF
# Terraform outputs for ${ENVIRONMENT} environment
# Generated by sync-terraform-outputs.sh
# DO NOT EDIT MANUALLY - This file is auto-generated
# To update: Run 'terraform apply' then 'scripts/sync-terraform-outputs.sh ${ENVIRONMENT}'

# Required deployment variables
AWS_S3_BUCKET=${BUCKET_NAME}
AWS_CLOUDFRONT_ID=${CLOUDFRONT_ID}
AWS_REGION=${AWS_REGION}

# CloudFront configuration
CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
WEBSITE_URL=${WEBSITE_URL}

# S3 bucket information
AWS_S3_BUCKET_ARN=${BUCKET_ARN}

# Environment-specific CloudFront domain variables
# For production: AWS_CLOUDFRONT_DOMAIN
# For development: AWS_CLOUDFRONT_DOMAIN_DEV
# For staging: AWS_CLOUDFRONT_DOMAIN_STAGING
$(if [ "$ENVIRONMENT" = "prod" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}"
elif [ "$ENVIRONMENT" = "development" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN_DEV=${CLOUDFRONT_DOMAIN}"
elif [ "$ENVIRONMENT" = "staging" ]; then
    echo "AWS_CLOUDFRONT_DOMAIN_STAGING=${CLOUDFRONT_DOMAIN}"
fi)

# For Nuxt.js runtime config
NUXT_PUBLIC_CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
NUXT_PUBLIC_WEBSITE_URL=${WEBSITE_URL}

# Deployment command (for reference)
# DEPLOY_COMMAND=${DEPLOY_COMMAND}
EOF

# Validate that required outputs are present
if [ -z "$BUCKET_NAME" ]; then
    echo -e "${YELLOW}⚠️  Warning: S3 bucket name not found in Terraform outputs${NC}"
fi

if [ -z "$CLOUDFRONT_ID" ]; then
    echo -e "${YELLOW}⚠️  Warning: CloudFront distribution ID not found in Terraform outputs${NC}"
fi

if [ -z "$CLOUDFRONT_DOMAIN" ]; then
    echo -e "${YELLOW}⚠️  Warning: CloudFront domain name not found in Terraform outputs${NC}"
fi

# Go back to project root
cd - > /dev/null

echo -e "\n${GREEN}✅ Terraform outputs synced!${NC}"
echo -e "${BLUE}Files created:${NC}"
echo -e "  - ${INFRA_DIR}/terraform-outputs.json"
echo -e "  - ${INFRA_DIR}/.env.terraform"
echo ""
echo -e "${BLUE}💡 To use in Nuxt.js:${NC}"
echo -e "  ${YELLOW}source ${INFRA_DIR}/.env.terraform${NC}"
echo ""
echo -e "${BLUE}💡 To use in deployment:${NC}"
echo -e "  ${YELLOW}source ${INFRA_DIR}/.env.terraform && ./aws-deploy.sh ${ENVIRONMENT}${NC}"

