#!/bin/bash
# ===========================================
# Sync Terraform Outputs to JSON and ENV Files
# ===========================================
# This script regenerates terraform-outputs.json and .env.terraform
# files from the current Terraform state to prevent stale data issues.
#
# Usage: ./scripts/sync-terraform-outputs.sh [environment]
# Example: ./scripts/sync-terraform-outputs.sh development
#          ./scripts/sync-terraform-outputs.sh production
#          ./scripts/sync-terraform-outputs.sh all

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENVIRONMENT="${1:-}"

# Function to sync outputs for a specific environment
sync_environment() {
	local env="$1"
	local env_dir="${PROJECT_ROOT}/infrastructure/environments/${env}"

	if [[ ! -d "${env_dir}" ]]; then
		echo -e "${YELLOW}⚠️  Environment directory not found: ${env}${NC}"
		return 1
	fi

	if [[ ! -d "${env_dir}/.terraform" ]]; then
		echo -e "${YELLOW}⚠️  Terraform not initialized for ${env}${NC}"
		echo -e "   Run: cd ${env_dir} && terraform init"
		return 1
	fi

	echo -e "\n${BLUE}📋 Syncing outputs for ${env}...${NC}"
	cd "${env_dir}"

	# Generate terraform-outputs.json
	echo -e "  Generating terraform-outputs.json..."
	terraform output -json | jq '.' > terraform-outputs.json

	# Generate .env.terraform
	echo -e "  Generating .env.terraform..."
	cat > .env.terraform << EOF
# Terraform outputs for ${env} environment
# Generated by sync-terraform-outputs.sh
# DO NOT EDIT MANUALLY - This file is auto-generated
# To update: Run 'terraform apply' then 'scripts/sync-terraform-outputs.sh ${env}'

# Required deployment variables
AWS_S3_BUCKET=$(terraform output -raw bucket_name 2>/dev/null || echo "")
AWS_CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
AWS_REGION=eu-central-1

# CloudFront configuration
CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")
WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")

# S3 bucket information
AWS_S3_BUCKET_ARN=$(terraform output -raw bucket_arn 2>/dev/null || echo "")

# Deployment command (for reference)
# DEPLOY_COMMAND=$(terraform output -raw deploy_command 2>/dev/null || echo "")
EOF

	# Verify the outputs
	local cloudfront_id=$(jq -r '.cloudfront_distribution_id.value' terraform-outputs.json)
	echo -e "${GREEN}✓ Synced ${env}${NC}"
	echo -e "  CloudFront ID: ${cloudfront_id}"

	cd - >/dev/null
}

# Main logic
case "${ENVIRONMENT}" in
	"")
		echo -e "${RED}❌ Error: Environment not specified${NC}"
		echo -e "Usage: $0 <environment>"
		echo -e "       $0 all"
		echo -e "\nAvailable environments:"
		ls -1 "${PROJECT_ROOT}/infrastructure/environments" | grep -v README
		exit 1
		;;
	all)
		echo -e "${BLUE}🔄 Syncing all environments...${NC}"
		for env in development staging production; do
			sync_environment "${env}" || true
		done
		;;
	*)
		sync_environment "${ENVIRONMENT}"
		;;
esac

echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Terraform outputs synced successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

echo -e "\n${BLUE}💡 Tip: Run this script after 'terraform apply' to keep outputs in sync${NC}"
